//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPro1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seferler
    {
        public string Nerden { get; set; }
        public string Nereye { get; set; }
        public string Saati { get; set; }
        public string Yetişkin_Fiyatı { get; set; }
        public string Cocuk_Fiyatı { get; set; }
    }
}
